on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: assignmentselise.azurecr.io
        username: ${{ secrets.acr_assignmentselise_username }}
        password: ${{ secrets.acr_assignmentselise_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t assignmentselise.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push assignmentselise.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep my-apache2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace my-apache2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: my-apache2
        container-registry-url: assignmentselise.azurecr.io
        container-registry-username: ${{ secrets.acr_assignmentselise_username }}
        container-registry-password: ${{ secrets.acr_assignmentselise_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: my-apache2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          assignmentselise.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
